import { Certificate } from "../types";
import { Award, Sparkles, Download, Calendar, Copy, Check } from "lucide-react";
import { useState } from "react";

interface CertificatesViewProps {
  certificates: Certificate[];
}

export default function CertificatesView({ certificates }: CertificatesViewProps) {
  const [selectedCert, setSelectedCert] = useState<Certificate | null>(null);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  const handlePrint = () => {
    window.print();
  };

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="border-b border-slate-200 pb-5 mb-8">
        <h2 className="text-2xl font-bold text-slate-900 leading-tight">My Credentials & Certificates</h2>
        <p className="mt-1.5 text-xs text-slate-500">
          Verify and print your official AI-evaluated diplomas. Every diploma features a unique appraisal generated by Google's Gemini LLM.
        </p>
      </div>

      {certificates.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-slate-200 p-12 text-center bg-white">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-indigo-50 text-indigo-600">
            <Award className="h-6 w-6" />
          </div>
          <h3 className="mt-4 text-base font-bold text-slate-900">No Certificates Earned Yet</h3>
          <p className="mt-1 text-xs text-slate-500 max-w-md mx-auto">
            Complete all modules of any course and achieve at least 70% in each modular assessment to unlock your official credential.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
          {/* List of Certificates (Left/Top) */}
          <div className="lg:col-span-4 flex flex-col gap-3">
            {certificates.map((cert) => (
              <button
                key={cert.id}
                onClick={() => setSelectedCert(cert)}
                className={`group text-left rounded-xl border p-4 transition-all flex items-start gap-3.5 cursor-pointer ${
                  selectedCert?.id === cert.id
                    ? "border-indigo-600 bg-indigo-50/30 font-bold shadow-sm"
                    : "border-slate-200 bg-white hover:border-slate-300"
                }`}
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-600 border border-amber-100">
                  <Award className="h-5.5 w-5.5" />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="text-sm font-bold text-slate-900 leading-tight group-hover:text-indigo-600 transition-colors truncate">
                    {cert.courseTitle}
                  </h4>
                  <p className="text-[11px] font-mono text-slate-400 mt-0.5">
                    Issued: {new Date(cert.issuedAt).toLocaleDateString()}
                  </p>
                  <p className="text-[10px] uppercase font-bold tracking-wider text-emerald-600 mt-1 font-mono">
                    Grade achieved: {cert.grade}%
                  </p>
                </div>
              </button>
            ))}
          </div>

          {/* Detailed Selected Certificate Framed preview (Right/Bottom) */}
          <div className="lg:col-span-8 flex flex-col gap-4">
            {selectedCert ? (
              <div className="flex flex-col gap-4">
                {/* Certificate frame wrapper */}
                <div 
                  id="print-certificate-card"
                  className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 sm:p-14 text-left shadow-lg print:border-2 print:shadow-none"
                >
                  {/* Subtle Elegant Minimalist Grid Corner Markers */}
                  <div className="absolute top-4 left-4 h-3 w-3 border-t border-l border-slate-300"></div>
                  <div className="absolute top-4 right-4 h-3 w-3 border-t border-r border-slate-300"></div>
                  <div className="absolute bottom-4 left-4 h-3 w-3 border-b border-l border-slate-300"></div>
                  <div className="absolute bottom-4 right-4 h-3 w-3 border-b border-r border-slate-300"></div>

                  {/* Left Asymmetric accent border */}
                  <div className="absolute left-0 top-0 bottom-0 w-2.5 bg-indigo-600"></div>

                  {/* Content grid */}
                  <div className="relative z-10 pl-2">
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between border-b border-slate-100 pb-5 gap-4">
                      <div>
                        <span className="font-mono text-[9px] font-black tracking-[0.3em] text-indigo-600 uppercase">
                          Official Competency Credentials
                        </span>
                        <h3 className="text-xl font-bold text-slate-900 tracking-tight font-sans mt-0.5">
                          I-LMS SYSTEM DIRECTORY
                        </h3>
                      </div>
                      <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-slate-50 border border-slate-100/90 text-slate-700">
                        <Award className="h-5.5 w-5.5 text-indigo-600" />
                      </div>
                    </div>

                    <div className="my-8">
                      <span className="font-mono text-[10px] text-slate-400 uppercase tracking-widest block font-bold leading-none">
                        Interactive Certificate of Mastery
                      </span>
                      <p className="text-xs text-slate-400 mt-1">This document verifies that the student listed below has completed all curriculum assessments.</p>
                      
                      <div className="mt-6 mb-8">
                        <span className="font-mono text-[10px] text-slate-400 uppercase block font-medium">RECIPIENT</span>
                        <h2 className="text-3xl sm:text-5xl font-extralight text-slate-900 tracking-tight mt-1 leading-none font-sans">
                          {selectedCert.studentName}
                        </h2>
                      </div>

                      <div className="space-y-1">
                        <span className="font-mono text-[10px] text-slate-400 uppercase block font-medium">ACCREDITED PROGRAM</span>
                        <h4 className="text-lg sm:text-2xl font-bold tracking-tight text-slate-800 leading-snug">
                          {selectedCert.courseTitle}
                        </h4>
                        <p className="text-xs text-slate-500 leading-relaxed font-sans max-w-xl">
                          Satisfied all competency-based module learning checks, interactive development workspace tasks, and formal algorithm validations.
                        </p>
                      </div>
                    </div>

                    {/* AI Evaluation appraisal column */}
                    <div className="rounded-xl border border-slate-100 bg-slate-50/50 p-4.5 font-sans mb-8">
                      <div className="flex items-center gap-1.5 text-[9px] font-mono tracking-widest text-slate-500 uppercase font-black mb-1.5">
                        <Sparkles className="h-3 w-3 text-indigo-500 shrink-0" />
                        Gemini AI Evaluation Registry
                      </div>
                      <p className="text-xs text-slate-600 italic leading-relaxed font-serif pl-3 border-l-2 border-indigo-500/50">
                        "{selectedCert.aiAppraisal}"
                      </p>
                    </div>

                    {/* Signatures & Seal */}
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 border-t border-slate-100 pt-6">
                      <div className="font-sans text-left">
                        <span className="font-mono text-[8px] tracking-widest text-slate-400 block font-bold uppercase">ISSUED TO</span>
                        <span className="text-xs font-bold text-slate-800 font-sans block mt-0.5">{selectedCert.studentName}</span>
                        <span className="font-mono text-[8.5px] text-indigo-600 block leading-none font-bold mt-1">VERIFIED SCHOLAR ID</span>
                      </div>

                      <div className="font-sans text-left">
                        <span className="font-mono text-[8px] tracking-widest text-slate-400 block font-bold uppercase">VERIFICATION COMPILER</span>
                        <span className="font-mono text-xs font-bold text-slate-800 block mt-0.5">{selectedCert.verificationCode}</span>
                        <span className="font-mono text-[8.5px] text-slate-400 block leading-none mt-1">GPA ACHIEVED: {selectedCert.grade}%</span>
                      </div>
                      
                      <div className="font-sans text-left">
                        <span className="font-mono text-[8px] tracking-widest text-slate-400 block font-bold uppercase">ACCREDITATION AGENCY</span>
                        <span className="font-mono text-[11px] font-bold text-slate-800 flex items-center gap-1 mt-0.5">
                          <Calendar className="h-3 w-3 text-indigo-500" />
                          {new Date(selectedCert.issuedAt).toLocaleDateString()}
                        </span>
                        <span className="font-mono text-[8.5px] text-slate-600 font-bold uppercase tracking-wider block mt-1">I-LMS ACADEMY</span>
                      </div>
                    </div>

                    {/* Minimalist Signature block for printable formality */}
                    <div className="mt-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-t border-slate-100/60 pt-5 text-[10px] text-slate-400 font-mono">
                      <span>Authority: Verified Secure Hash: SHA-256/{selectedCert.id.slice(0, 12)}</span>
                      <span>Digital Accreditation Seal verified by Gemini AI LLM</span>
                    </div>
                  </div>
                </div>

                {/* Print button controls */}
                <div className="flex items-center justify-between gap-4 bg-slate-50 border border-slate-200/80 rounded-xl p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <button
                      onClick={() => handleCopyCode(selectedCert.verificationCode)}
                      className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 px-3 py-1.5 text-xs font-semibold text-slate-700 transition"
                    >
                      {copiedCode === selectedCert.verificationCode ? (
                        <>
                          <Check className="h-3.5 w-3.5 text-emerald-500" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5" />
                          Copy Verification Code
                        </>
                      )}
                    </button>
                  </div>

                  <button
                    onClick={handlePrint}
                    className="flex items-center gap-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-100 transition"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Print Diploma (PDF)
                  </button>
                </div>
              </div>
            ) : (
              <div className="rounded-2xl border border-slate-200 p-12 text-center bg-white flex flex-col items-center justify-center h-full min-h-[300px]">
                <Award className="h-10 w-10 text-slate-300" />
                <h4 className="mt-3.5 font-bold text-slate-700">Select Certificate Entry</h4>
                <p className="mt-1 text-xs text-slate-400 max-w-xs leading-relaxed">
                  Click on an earned credential in the left list to review its gold seal frame, validation credentials, and AI appraisal report.
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
