export interface Question {
  id: string;
  question: string;
  options: string[];
  answerIndex: number;
  explanation?: string;
}

export interface Quiz {
  questions: Question[];
}

export interface Module {
  id: string;
  title: string;
  description: string;
  videoUrl: string; // Embeddable YouTube URL (e.g., https://www.youtube.com/embed/...)
  duration: string;
  quiz: Quiz;
}

export interface Course {
  id: string;
  title: string;
  description: string;
  category: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  duration: string;
  rating: number;
  instructor: string;
  thumbnailUrl: string;
  modules: Module[];
}

export interface ModuleProgress {
  completed: boolean;
  quizScore?: number; // percentage, e.g. 85
  quizPassed?: boolean;
}

export interface CourseProgress {
  courseId: string;
  completedModules: string[]; // List of completed module IDs
  quizScores: Record<string, number>; // Record of module ID to score
  completed: boolean;
  completedAt?: string;
  certificateId?: string;
}

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  photoURL?: string;
  title?: string;
  bio?: string;
  joinedAt: string;
}

export interface Certificate {
  id: string;
  uid: string;
  courseId: string;
  courseTitle: string;
  studentName: string;
  issuedAt: string;
  grade: number;
  verificationCode: string;
  aiAppraisal: string; // Customized educational feedback generated by AI
}
